apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: mogambo
  labels:
    app: catalogue
    env: dev
spec:
  template:
    metadata:
      labels:
        app: catalogue
        env: dev
    spec:
      tolerations:
        - key: "dedicate"
          operator: "Equal"
          value: "catalogue"
          effect: "NoExecute"
      containers:
        - name: catalogue
          image: schoolofdevops/catalogue
          imagePullPolicy: Always
          ports:
            - containerPort: 80
