apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    app: front-end
    role: ui
    tier: front
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - frontend
          topologyKey: kubernetes.io/hostname
  containers:
    - name: front-end
      image: schoolofdevops/frontend:latest
      ports:
        - containerPort: 8079  
  nodeSelector:
    zone: 'aaa'
