apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    app: front-end
    role: ui
    tier: front
spec:
  containers:
    - name: front-end
      image: schoolofdevops/frontend:latest
      ports:
        - containerPort: 8079  
  nodeSelector:
    zone: 'aaa'
