apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: nginx
    role: ui
    tier: front
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
      - name: data
        mountPath: /opt/d1
    - name: loop
      image: schoolofdevops/loop
      volumeMounts:
      - name: data
        mountPath: /opt/d1
  volumes:
  - name: data
    emptyDir: {}
