apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    app: vote
    role: ui
    tier: front
spec:
  containers:
    - name: vote
      image: schoolofdevops/vote:latest
      ports:
        - containerPort: 80
